import type { Metadata } from "next";import Link from"next/link";import{CheckCircle2,ArrowRight,Phone}from"lucide-react";
export const metadata:Metadata={title:"Hakkımızda | Antalya Fiber",description:"Antalya Fiber; Antalya'da fiber optik, network, yapısal kablolama, güvenlik kamera sistemleri, servis ve bakım çözümleri sunar.",alternates:{canonical:"/hakkimizda"},openGraph:{title:"Hakkımızda | Antalya Fiber",description:"Fiber optik, network, yapısal kablolama ve güvenlik sistemlerinde keşiften teknik desteğe saha çözümleri.",url:"/hakkimizda",type:"website"}};
const values=["İhtiyaca göre keşif ve altyapı planlama","Fiber optik kurulum, sonlandırma ve test","Network ve yapısal kablolama uygulamaları","Güvenlik kamera sistemleri","Servis, bakım ve arıza müdahalesi"];
export default function Page(){return <main>
<section className="pagehero"><div className="wrap"><span>ANTALYA FİBER</span><h1>Teknoloji altyapınızın sahadaki çözüm ortağı</h1><p>Fiber optik, network ve güvenlik altyapılarında keşiften kuruluma, testten teknik desteğe kadar sahada çalışan çözümler.</p></div></section>
<section className="section"><div className="wrap aboutintro"><div className="aboutstory"><div className="eyebrow blue">HAKKIMIZDA</div><h2>Altyapıyı yalnızca kurmuyor, doğru çalışmasını sağlıyoruz.</h2><p className="lead">Antalya Fiber olarak işletmelerin iletişim ve güvenlik altyapısı ihtiyaçlarına sahada çözüm üretiyoruz. Fiber optik altyapı, network ve yapısal kablolama, güvenlik kamera sistemleri ile servis ve onarım çalışmalarını tek noktadan ele alıyoruz.</p><p className="lead">Her projede önce ihtiyacı ve mevcut altyapıyı değerlendiriyor; ardından uygun çözümü planlıyor, uyguluyor, test ediyor ve devreye alıyoruz. Amacımız yalnızca kurulumu tamamlamak değil, düzenli, yönetilebilir ve sürdürülebilir bir altyapı teslim etmek.</p></div><figure className="aboutreal"><img src="/assets/projects/SİSTEM ODASI FİBER P-P (2).jpg" alt="Antalya Fiber tarafından gerçekleştirilen fiber optik sistem odası uygulaması"/><figcaption>Gerçek saha uygulamalarımızdan</figcaption></figure></div></section>
<section className="section soft"><div className="wrap detailgrid"><div><div className="eyebrow blue">ÇALIŞMA YAKLAŞIMIMIZ</div><h2>Keşiften devreye almaya kontrollü süreç</h2><p className="lead">İhtiyaca uygun ürün ve altyapı seçimi, temiz saha uygulaması, ölçüm ve test süreçleriyle projeyi bütün olarak yönetiyoruz. Kurulum sonrasında servis ve bakım ihtiyacında da altyapının devamlılığını destekliyoruz.</p><Link href="/hizmetler" className="more">Hizmetlerimizi inceleyin →</Link></div><div className="featurelist">{values.map(x=><div key={x}><CheckCircle2/><b>{x}</b></div>)}</div></div></section>
<section className="aboutstats"><div className="wrap aboutstatgrid"><div><strong>Fiber Optik</strong><span>Kurulum · Sonlandırma · Test</span></div><div><strong>Network</strong><span>Yapısal Kablolama · Kabinet</span></div><div><strong>Güvenlik</strong><span>IP Kamera · Kayıt Sistemleri</span></div><div><strong>Teknik Servis</strong><span>Bakım · Arıza Müdahalesi</span></div></div></section>
<section className="cta"><div className="wrap ctawrap"><div><div className="eyebrow">PROJENİZİ KONUŞALIM</div><h2>Altyapı ihtiyacınızı birlikte planlayalım.</h2><p>Fiber, network, kamera veya teknik servis ihtiyacınız için Antalya Fiber'e ulaşın.</p></div><div className="actions"><Link className="btn ctaphone" href="/iletisim">Keşif Talep Et <ArrowRight size={18}/></Link><a className="btn ghost" href="tel:+905326222235"><Phone size={18}/>0532 622 22 35</a></div></div></section>
</main>}