import Link from "next/link";
import { Cable, Camera, Settings, Network, ArrowRight, CheckCircle2, Phone } from "lucide-react";

const services=[
{icon:Cable,title:"Fiber Optik Altyapı",href:"/hizmetler/fiber-optik",text:"Fiber kablo tesisatı, sonlandırma, ölçüm, test ve mevcut hatlarda arıza tespiti."},
{icon:Network,title:"Network & Yapısal Kablolama",href:"/hizmetler/network-kablolama",text:"Cat6/Cat6A, kabinet, patch panel, data prizi ve kurumsal network altyapısı."},
{icon:Camera,title:"Güvenlik Kamera Sistemleri",href:"/hizmetler/guvenlik-kamera",text:"IP kamera, kayıt, görüntüleme, uzaktan erişim ve güvenlik altyapıları."},
{icon:Settings,title:"Servis & Onarım",href:"/hizmetler/servis-onarim",text:"Arıza tespiti, bakım ve hızlı saha müdahalesiyle kesintileri en aza indiren teknik servis."}
];
const partners=["Cisco","Aruba","HP","Ruckus","SonicWall","Legrand","EnGenius","AMP","LS","EtherWAN"];
export default function Home(){return <main>
<section className="homehero"><div className="wrap herogrid"><div><div className="eyebrow">ANTALYA'NIN TEKNOLOJİ ALTYAPI ÇÖZÜMLERİ</div><h1>Güçlü altyapı.<br/><span>Kesintisiz bağlantı.</span></h1><p>Fiber optik, yapısal kablolama, network ve güvenlik sistemlerinde keşiften kuruluma, testten teknik servise kadar uçtan uca çözümler.</p><div className="actions"><Link href="/iletisim" className="btn primary">Ücretsiz Keşif <ArrowRight size={18}/></Link><Link href="/hizmetler" className="btn ghost">Hizmetleri İncele</Link></div></div><div className="signal"><div className="signalcore"><Cable size={56}/><b>FIBER</b><small>NETWORK · GÜVENLİK</small></div></div></div></section>
<section className="section"><div className="wrap"><div className="sectionhead"><div className="eyebrow blue">HİZMETLERİMİZ</div><h2>Altyapınız için doğru teknoloji,<br/>doğru uygulama</h2><p>İhtiyacınızı sahada analiz ediyor, doğru altyapıyı planlıyor ve devreye alıyoruz.</p></div><div className="servicegrid">{services.map(({icon:Icon,title,href,text})=><Link className="servicecard" href={href} key={title}><div className="iconbox"><Icon/></div><h3>{title}</h3><p>{text}</p><b>Detayları incele →</b></Link>)}</div></div></section>
<section className="section soft"><div className="wrap twocol"><div><div className="eyebrow blue">ANTALYA FİBER</div><h2>Sahada çalışan, sonuç odaklı altyapı çözümleri</h2><p className="lead">İletişim ve güvenlik altyapınızı yalnızca kurmuyor; planlama, test, devreye alma ve teknik destek süreçlerini birlikte yönetiyoruz.</p><Link href="/hakkimizda" className="more">Bizi yakından tanıyın →</Link></div><div className="checkcard">{["Fiber optik kurulum ve sonlandırma","Network ve yapısal kablolama","Güvenlik kamera altyapıları","Servis, bakım ve arıza müdahalesi"].map(x=><div key={x}><CheckCircle2/><span>{x}</span></div>)}</div></div></section>
<section className="partnerbar"><div className="wrap"><div className="eyebrow blue center">ÇÖZÜM ORTAKLARIMIZ</div><div className="partners">{partners.map(x=><span key={x}>{x}</span>)}</div></div></section>
<section className="section"><div className="wrap"><div className="sectionhead center"><div className="eyebrow blue">REFERANSLAR</div><h2>Uzun soluklu iş ilişkileri</h2><p>Farklı sektörlerde altyapı ve teknoloji ihtiyaçlarına çözüm üretiyoruz.</p></div><div className="refgrid">{["HEXA","TARKO","HERA","EKSEN"].map(x=><div className="refitem" key={x}>{x}</div>)}</div><div className="center topgap"><Link href="/referanslar" className="more">Referansları incele →</Link></div></div></section>
<section className="cta"><div className="wrap ctawrap"><div><div className="eyebrow">ÜCRETSİZ KEŞİF</div><h2>Projenizi birlikte planlayalım.</h2><p>Fiber altyapı, network, kamera sistemi veya teknik servis ihtiyacınız için bize ulaşın.</p></div><a className="btn ctaphone" href="tel:+905326222235"><Phone size={19}/>0532 622 22 35</a></div></section>
</main>}