import Link from "next/link";
import { Cable, Camera, Settings, Network, ArrowRight, CheckCircle2, Phone } from "lucide-react";

const services=[
{icon:Cable,title:"Fiber Optik Altyapı",href:"/hizmetler/fiber-optik",text:"Fiber kablo tesisatı, sonlandırma, ölçüm, test ve mevcut hatlarda arıza tespiti."},
{icon:Network,title:"Network & Yapısal Kablolama",href:"/hizmetler/network-kablolama",text:"Cat6/Cat6A, kabinet, patch panel, data prizi ve kurumsal network altyapısı."},
{icon:Camera,title:"Güvenlik Kamera Sistemleri",href:"/hizmetler/guvenlik-kamera",text:"IP kamera, kayıt, görüntüleme, uzaktan erişim ve güvenlik altyapıları."},
{icon:Settings,title:"Servis & Onarım",href:"/hizmetler/servis-onarim",text:"Arıza tespiti, bakım ve hızlı saha müdahalesiyle kesintileri en aza indiren teknik servis."}
];
const partners=[["VGuard","https://static.wixstatic.com/media/5f9784_1d2d1db3319a430ea91f46f9ed7ceee3~mv2.png"],["SonicWall","https://static.wixstatic.com/media/5f9784_b40d7d3ddf994b6ca58e1027f75a0cdd~mv2.png"],["Ruckus","https://static.wixstatic.com/media/5f9784_b8ca0b85b18a47cda1d0f34bb4108550~mv2.png"],["LS","https://static.wixstatic.com/media/5f9784_5bbfb40bda7a4b34a87b9576064a9e40~mv2.png"],["Edge","https://static.wixstatic.com/media/5f9784_62fc69a4f5ec41a9b87cc870a66b7e93~mv2.png"],["AMP","https://static.wixstatic.com/media/5f9784_8e6085db01724c6f875827b76c7f70a8~mv2.png"],["Legrand","https://static.wixstatic.com/media/5f9784_93f6467e95a94429aa19ee9b72a4bd6f~mv2.png"],["Cisco","https://static.wixstatic.com/media/5f9784_254d250c28b24f8ab2a593ff17c48967~mv2.png"],["EtherWAN","https://static.wixstatic.com/media/5f9784_f5d67df0f29445bdb8cbb6a24475ca9e~mv2.png"],["HP","https://static.wixstatic.com/media/5f9784_e486e9934df54426b56b458ad293953f~mv2.png"],["EnGenius","https://static.wixstatic.com/media/5f9784_b20d400bfb55425f9f2c1097d0a25b6c~mv2.png"],["Aruba","https://static.wixstatic.com/media/5f9784_eedfe39e8d934c2e87a6c1f7159957a2~mv2.png"]];
export default function Home(){return <main>
<section className="homehero visualhero"><div className="wrap herogrid"><div><div className="eyebrow">ANTALYA'NIN TEKNOLOJİ ALTYAPI ÇÖZÜMLERİ</div><h1>Güçlü altyapı.<br/><span>Kesintisiz bağlantı.</span></h1><p>Fiber optik, yapısal kablolama, network ve güvenlik sistemlerinde keşiften kuruluma, testten teknik servise kadar uçtan uca çözümler.</p><div className="actions"><Link href="/iletisim" className="btn primary">Ücretsiz Keşif <ArrowRight size={18}/></Link><Link href="/hizmetler" className="btn ghost">Hizmetleri İncele</Link></div></div><div className="heroimage"><img src="https://blogs.kent.ac.uk/uk-eu-ref-watch/files/2021/04/pexels-brett-sayles-4425157.jpg" alt="Fiber optik patch panel ve bağlantı altyapısı"/><div className="imagebadge"><b>Fiber Optik Altyapı</b><span>Yüksek hızlı, düzenli ve ölçeklenebilir bağlantı</span></div></div></div></section>
<section className="section"><div className="wrap"><div className="sectionhead"><div className="eyebrow blue">HİZMETLERİMİZ</div><h2>Altyapınız için doğru teknoloji,<br/>doğru uygulama</h2><p>İhtiyacınızı sahada analiz ediyor, doğru altyapıyı planlıyor ve devreye alıyoruz.</p></div><div className="servicegrid">{services.map(({icon:Icon,title,href,text})=><Link className="servicecard" href={href} key={title}><div className="iconbox"><Icon/></div><h3>{title}</h3><p>{text}</p><b>Detayları incele →</b></Link>)}</div></div></section>
<section className="section soft"><div className="wrap twocol"><div className="aboutimage"><img src="https://www.senter-e.com/Content/uploads/2022174246/202208200931007abd452e04064c4e8f1be5cc0b840854.jpg" alt="Fiber optik füzyon sonlandırma işlemi"/></div><div className="aboutcopy"><div className="eyebrow blue">ANTALYA FİBER</div><h2>Sahada çalışan, sonuç odaklı altyapı çözümleri</h2><p className="lead">İletişim ve güvenlik altyapınızı yalnızca kurmuyor; planlama, test, devreye alma ve teknik destek süreçlerini birlikte yönetiyoruz.</p><Link href="/hakkimizda" className="more">Bizi yakından tanıyın →</Link></div><div className="checkcard">{["Fiber optik kurulum ve sonlandırma","Network ve yapısal kablolama","Güvenlik kamera altyapıları","Servis, bakım ve arıza müdahalesi"].map(x=><div key={x}><CheckCircle2/><span>{x}</span></div>)}</div></div></section>
<section className="partnerbar"><div className="wrap"><div className="eyebrow blue center">ÇÖZÜM ORTAKLARIMIZ</div><div className="partners partnerlogos">{partners.map(([name,img])=><span key={name}><img src={img} alt={name+" çözüm ortağı logosu"}/><small>{name}</small></span>)}</div></div></section>
<section className="section"><div className="wrap"><div className="sectionhead center"><div className="eyebrow blue">REFERANSLAR</div><h2>Uzun soluklu iş ilişkileri</h2><p>Farklı sektörlerde altyapı ve teknoloji ihtiyaçlarına çözüm üretiyoruz.</p></div><div className="refgrid">{[["HEXA","https://static.wixstatic.com/media/0fa92a967c76420a83938ecadb5ba4f2.png"],["TARKO","https://static.wixstatic.com/media/8083f7b02b824feaac22f26d88b3f5a8.png"],["HERA","https://static.wixstatic.com/media/34a050f696dc4d18978e83874a0b82bc.png"],["EKSEN","https://static.wixstatic.com/media/b79c5c268339492891db2d787acafa98.png"]].map(([name,img])=><div className="refitem reflogo" key={name}><img src={img} alt={name+" müşteri logosu"}/><b>{name}</b></div>)}</div><div className="center topgap"><Link href="/referanslar" className="more">Referansları incele →</Link></div></div></section>
<section className="cta"><div className="wrap ctawrap"><div><div className="eyebrow">ÜCRETSİZ KEŞİF</div><h2>Projenizi birlikte planlayalım.</h2><p>Fiber altyapı, network, kamera sistemi veya teknik servis ihtiyacınız için bize ulaşın.</p></div><a className="btn ctaphone" href="tel:+905326222235"><Phone size={19}/>0532 622 22 35</a></div></section>
</main>}