import Link from "next/link";
import { Cable, Camera, Settings, Network, ArrowRight, CheckCircle2, Phone } from "lucide-react";

const services=[
{icon:Cable,title:"Fiber Optik Altyapı",href:"/hizmetler/fiber-optik",text:"Fiber kablo tesisatı, sonlandırma, ölçüm, test ve mevcut hatlarda arıza tespiti."},
{icon:Network,title:"Network & Yapısal Kablolama",href:"/hizmetler/network-kablolama",text:"Cat6/Cat6A, kabinet, patch panel, data prizi ve kurumsal network altyapısı."},
{icon:Camera,title:"Güvenlik Kamera Sistemleri",href:"/hizmetler/guvenlik-kamera",text:"IP kamera, kayıt, görüntüleme, uzaktan erişim ve güvenlik altyapıları."},
{icon:Settings,title:"Servis & Onarım",href:"/hizmetler/servis-onarim",text:"Arıza tespiti, bakım ve hızlı saha müdahalesiyle kesintileri en aza indiren teknik servis."}
];
const partners=[["VGuard","/assets/partners/vguard.png"],["SonicWall","/assets/partners/sonicwall.png"],["Ruckus","/assets/partners/ruckus.png"],["LS","/assets/partners/ls.png"],["Edge","/assets/partners/logo-edge.png"],["AMP","/assets/partners/logo-amp.gif"],["Legrand","/assets/partners/legrand.png"],["Cisco","/assets/partners/logo-cisco.png"],["EtherWAN","/assets/partners/ether.png"],["HP","/assets/partners/hp.png"],["EnGenius","/assets/partners/engenius.png"],["Aruba","/assets/partners/aruba_logo.png"]];
const projects=["11160262_378318772367257_2084715801_n.jpg","20141126_153250.jpg","ANA BİNA 2. KAT.jpg","D8 A (2).jpg","IMG-20150529-WA0003.jpg","IMG-20180117-WA0007.jpg","IMG-20180117-WA0008.jpg","IMG-20180117-WA0010.jpg","IMG-20180117-WA0012.jpg","IMG-20180117-WA0025.jpg","LOJMAN (2).jpg","SİSTEM ODASI FİBER P-P (2).jpg","WP_20140304_005.jpg","WP_20150414_007.jpg"];
export default function Home(){return <main>
<section className="homehero visualhero"><div className="wrap herogrid"><div><div className="eyebrow">ANTALYA'NIN TEKNOLOJİ ALTYAPI ÇÖZÜMLERİ</div><h1>Güçlü altyapı.<br/><span>Kesintisiz bağlantı.</span></h1><p>Fiber optik, yapısal kablolama, network ve güvenlik sistemlerinde keşiften kuruluma, testten teknik servise kadar uçtan uca çözümler.</p><div className="actions"><Link href="/iletisim" className="btn primary">Ücretsiz Keşif <ArrowRight size={18}/></Link><Link href="/hizmetler" className="btn ghost">Hizmetleri İncele</Link></div></div><div className="heroimage"><img src="/assets/projects/SİSTEM ODASI FİBER P-P (2).jpg" alt="Fiber optik patch panel ve bağlantı altyapısı"/><div className="imagebadge"><b>Fiber Optik Altyapı</b><span>Yüksek hızlı, düzenli ve ölçeklenebilir bağlantı</span></div></div></div></section>
<section className="section"><div className="wrap"><div className="sectionhead"><div className="eyebrow blue">HİZMETLERİMİZ</div><h2>Altyapınız için doğru teknoloji,<br/>doğru uygulama</h2><p>İhtiyacınızı sahada analiz ediyor, doğru altyapıyı planlıyor ve devreye alıyoruz.</p></div><div className="servicegrid">{services.map(({icon:Icon,title,href,text})=><Link className="servicecard" href={href} key={title}><div className="iconbox"><Icon/></div><h3>{title}</h3><p>{text}</p><b>Detayları incele →</b></Link>)}</div></div></section>
<section className="section soft"><div className="wrap twocol"><div className="aboutimage"><img src="/assets/projects/IMG-20180117-WA0008.jpg" alt="Fiber optik füzyon sonlandırma işlemi"/></div><div className="aboutcopy"><div className="eyebrow blue">ANTALYA FİBER</div><h2>Sahada çalışan, sonuç odaklı altyapı çözümleri</h2><p className="lead">İletişim ve güvenlik altyapınızı yalnızca kurmuyor; planlama, test, devreye alma ve teknik destek süreçlerini birlikte yönetiyoruz.</p><Link href="/hakkimizda" className="more">Bizi yakından tanıyın →</Link></div><div className="checkcard">{["Fiber optik kurulum ve sonlandırma","Network ve yapısal kablolama","Güvenlik kamera altyapıları","Servis, bakım ve arıza müdahalesi"].map(x=><div key={x}><CheckCircle2/><span>{x}</span></div>)}</div></div></section>
<section className="partnerbar"><div className="wrap"><div className="eyebrow blue center">ÇÖZÜM ORTAKLARIMIZ</div><div className="partnerMarquee" aria-label="Çözüm ortaklarımız"><div className="partnerTrack">{[...partners,...partners].map(([name,img],i)=><div className="partnerLogo" key={name+i} aria-hidden={i>=partners.length}><img src={img} alt={i<partners.length?name+" çözüm ortağı logosu":""}/></div>)}</div></div></div></section>
<section className="section"><div className="wrap"><div className="sectionhead center"><div className="eyebrow blue">YAPTIĞIMIZ İŞLER</div><h2>Sahadan gerçek uygulamalar</h2><p>Fiber optik, network ve altyapı projelerimizden seçilmiş saha görüntüleri.</p></div><div className="projectgrid">{projects.map((img,i)=><figure className="projectitem" key={img}><img src={"/assets/projects/"+encodeURIComponent(img).replaceAll("%2F","/")} alt={"Antalya Fiber saha uygulaması "+(i+1)} loading="lazy"/></figure>)}</div><div className="center topgap"><Link href="/referanslar" className="more">Müşterilerimizi incele →</Link></div></div></section>
<section className="cta"><div className="wrap ctawrap"><div><div className="eyebrow">ÜCRETSİZ KEŞİF</div><h2>Projenizi birlikte planlayalım.</h2><p>Fiber altyapı, network, kamera sistemi veya teknik servis ihtiyacınız için bize ulaşın.</p></div><a className="btn ctaphone" href="tel:+905326222235"><Phone size={19}/>0532 622 22 35</a></div></section>
</main>}