import type{Metadata}from"next";import Link from"next/link";import{Cable,Network,Camera,Settings,ArrowRight,CheckCircle2,Phone}from"lucide-react";
export const metadata:Metadata={title:"Hizmetler | Antalya Fiber",description:"Antalya'da fiber optik altyapı, network ve yapısal kablolama, güvenlik kamera sistemleri ile teknik servis ve bakım çözümleri.",alternates:{canonical:"/hizmetler"}};
const services=[
{Icon:Cable,title:"Fiber Optik Altyapı",href:"/hizmetler/fiber-optik",text:"Fiber kablo tesisatı, füzyon ek, sonlandırma, ODF/patch panel düzenleme, ölçüm ve arıza tespiti.",img:"/assets/projects/SİSTEM ODASI FİBER P-P (2).jpg"},
{Icon:Network,title:"Network & Yapısal Kablolama",href:"/hizmetler/network-kablolama",text:"Cat6/Cat6A data kablolama, rack kabinet, patch panel, data prizi, etiketleme ve hat testleri.",img:"/assets/projects/ANA BİNA 2. KAT.jpg"},
{Icon:Camera,title:"Güvenlik Kamera Sistemleri",href:"/hizmetler/guvenlik-kamera",text:"IP kamera, NVR kayıt, uzaktan görüntüleme ve mevcut güvenlik altyapısının iyileştirilmesi.",img:"/assets/projects/IMG-20180117-WA0010.jpg"},
{Icon:Settings,title:"Servis & Onarım",href:"/hizmetler/servis-onarim",text:"Fiber, network ve güvenlik sistemlerinde yerinde arıza tespiti, bakım ve saha müdahalesi.",img:"/assets/projects/WP_20150414_007.jpg"}];
export default function Page(){return <main>
<section className="pagehero"><div className="wrap"><span>UZMANLIK ALANLARIMIZ</span><h1>Hizmetlerimiz</h1><p>Fiber optikten network altyapısına, güvenlik sistemlerinden teknik servise kadar keşif, kurulum, test ve destek süreçlerini sahada yönetiyoruz.</p></div></section>
<section className="section"><div className="wrap"><div className="sectionhead"><div className="eyebrow blue">ANTALYA FİBER</div><h2>İşletmenizin altyapısı için uçtan uca saha çözümleri</h2><p>İhtiyacı yerinde değerlendiriyor, uygun altyapıyı planlıyor ve kurulum sonrasında test ederek devreye alıyoruz.</p></div><div className="servicesShowcase">{services.map(({Icon,title,href,text,img})=><article className="serviceShowcase" key={title}><Link href={href} className="serviceShowcaseImage"><img src={img} alt={title+" saha uygulaması"} loading="lazy"/></Link><div className="serviceShowcaseBody"><div className="iconbox"><Icon/></div><h2>{title}</h2><p>{text}</p><Link className="more" href={href}>Hizmeti incele <ArrowRight size={16}/></Link></div></article>)}</div></div></section>
<section className="section soft"><div className="wrap detailgrid"><div><div className="eyebrow blue">NASIL ÇALIŞIYORUZ?</div><h2>Keşif, planlama, uygulama ve test.</h2><p className="lead">Sistemin yalnızca kurulmasına değil, düzenli ve sürdürülebilir çalışmasına odaklanıyoruz. Projeyi mevcut altyapı ve gerçek saha ihtiyacına göre ele alıyoruz.</p></div><div className="featurelist">{["Yerinde ihtiyaç ve altyapı analizi","Uygun çözüm ve güzergâh planlaması","Düzenli saha uygulaması ve sonlandırma","Kontrol, test ve devreye alma"].map(x=><div key={x}><CheckCircle2/><b>{x}</b></div>)}</div></div></section>
<section className="cta"><div className="wrap ctawrap"><div><div className="eyebrow">ÜCRETSİZ KEŞİF</div><h2>Hangi çözüme ihtiyacınız olduğunu birlikte belirleyelim.</h2><p>Projenizi anlatın; mevcut altyapınızı ve ihtiyacınızı değerlendirelim.</p></div><div className="actions"><Link className="btn ctaphone" href="/iletisim">Keşif Talep Et <ArrowRight size={18}/></Link><a className="btn ghost" href="tel:+905326222235"><Phone size={18}/>0532 622 22 35</a></div></div></section>
</main>}